// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE5OvTGrm4_r_bGLaHd67KrIRbTrV_4Pc',
    appId: '1:33236308739:web:362064cba966e9a5678f36',
    messagingSenderId: '33236308739',
    projectId: 'qastlay-cbe51',
    authDomain: 'qastlay-cbe51.firebaseapp.com',
    storageBucket: 'qastlay-cbe51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeIls8mwOvC7DmjIrSWLuJ3AqBiYKKohg',
    appId: '1:33236308739:android:f0ddde2b4cd0a50b678f36',
    messagingSenderId: '33236308739',
    projectId: 'qastlay-cbe51',
    storageBucket: 'qastlay-cbe51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfHGZJq5OJa3xxgXceg93hovMHeWq7SKs',
    appId: '1:33236308739:ios:c1c4fb4c157ba81a678f36',
    messagingSenderId: '33236308739',
    projectId: 'qastlay-cbe51',
    storageBucket: 'qastlay-cbe51.appspot.com',
    androidClientId: '33236308739-i72olah32bchuj28k439qlvef8q90dul.apps.googleusercontent.com',
    iosClientId: '33236308739-bgle093bpi0os9dv5957f8rtgrbjq45t.apps.googleusercontent.com',
    iosBundleId: 'com.example.qastlay',
  );

}